name: 🚀 Publicar GitHub Pages

on:
  workflow_dispatch:

concurrency:
  group: publish-pages
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write


jobs:
  publish-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: Build
        run: |
          pip install -r requirements.txt
          reflex init
          FRONTEND_PATH=/${{ github.event.repository.name }} reflex export --frontend-only --no-zip

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .web/_static/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4